name = News
description = Stemcell news layout
preview = preview.png
template = news-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer_first]   = First Footer
regions[footer_second]  = Second Footer
regions[footer_third]   = Third Footer

; Stylesheets
stylesheets[all][] = css/layouts/news/news.layout.css
